### ISSUE TITLE
Конфликт вызова с PHx

### ISSUE THREAD

**Issue by sashabeep** [DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddYMap#1]
Вероятно, я чо-то не так делаю, но когда пытаюсь вызвать

```
[[ddYMap?
&geoPos=`{latLng:[56.247329,43.404761],content:'Метка 1'},
{latLng:[56.220789,43.414185],content:'Метка 2'}`]]
```

с включенным PHx карта не рисуется и генерится такой скрипт:

```
$(function(){$("#map").ddYMap({placemarks: new Array({latLng:&_PHX_INTERNAL_091_&56.247329,43.404761&_PHX_INTERNAL_093_&,content:'Метка 1'}
```

то есть квадратные скобки заменяются на непонятно что... При отключении PHx всё работает
возможно, это и не issue вовсе, но странно, почему так

**Comment by Ronef** [comment]
Здравствуйте! Для начала, это  не к плагину, а к сниппету: https://github.com/DivanDesign/MODXEvo.snippet.ddYMap (плагин отвечает только за админку).

Но вообще, очевидно, что это PHx и даже к сниппету не имеет отношения. А по теме PHx, к сожалению, совсем нечего сказать, никогда его не использовали и не планируем. Слишком много жалоб на него ото всюду. Кажется, проблем он доставляет больше, чем преимуществ. Вы без него не можете обойтись? Я бы рекомендовал так и сделать.

**Comment by Segr** [comment]
Версия MODX какая?

**Comment by sashabeep** [comment]
Видимо, запутался в ссылках, пока смотрел, что к чему относится.
PHx, видимо, так странно разбирает последовательности
Версия modx 15

**Comment by Segr** [comment]
Первый раз на моей памяти действительно проблема в PHx.
Попробуйте в файле "phx.parser.class.inc.php" перед 

```
$replace = $modx->evalSnippets("[[".$snippet."]]");
```

вставить 

```
$snippet = str_replace($this->safetags[1],$this->safetags[2],$snippet);
```

**Comment by Segr** [comment]
можно и не патчить PHx, вот такой вызов работает

```
[[ddYMap?
&geoPos=`{latLng:new Array(56.247329,43.404761),content:'Метка 1'},
{latLng:new Array(56.220789,43.414185),content:'Метка 2'}`]]
```

**Comment by sashabeep** [comment]
Оба способа работают, спасибо.

**Comment by Ronef** [comment]
Ребят, если кто знает и может — запостите пожалуйста патч в репозиторий PHx.

_@Segr, ещё раз спасибо за помощь!_
